[build]
  command = "npm run build"
  publish = ".next"

# Handle wildcard subdomains
[[redirects]]
  from = "https://*.2nd.exchange/*"
  to = "https://2nd.exchange/:splat"
  status = 200
  force = true

# Fallback for all other routes to be handled by Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
