[build]
  command = "npm run build"
  publish = ".next"

# Use Next.js middleware with Netlify Edge Functions (default behavior)
# No need to explicitly define edge functions as Next.js middleware is automatically detected

# Handle wildcard subdomains at the DNS level with a CNAME record:
# *.2nd.exchange CNAME metasaransharma.netlify.app.

# Fallback for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
