[build]
  command = "npm run build"
  publish = ".next"

# Define edge functions
[[edge_functions]]
  path = "/*"
  function = "subdomain-router"

# Fallback for all other routes to be handled by Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
