[build]
  command = "npm run build"
  publish = ".next"

# Use the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Set domain environment variables
[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://2nd.exchange"
  NEXT_PUBLIC_DOMAIN = "2nd.exchange"
  NEXT_USE_NETLIFY_EDGE = "true"

# This is the key configuration for Netlify to properly handle wildcard subdomains
# It tells Netlify to proxy all subdomain requests to your main domain where
# your Next.js middleware can handle them

