[build]
  command = "npm run build"
  publish = ".next"

# Explicitly use the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Important: Configure Netlify to treat all subdomains as part of the same site
[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://2nd.exchange"
  NEXT_PUBLIC_DOMAIN = "2nd.exchange"

# Handle wildcard subdomains - this is critical for subdomain routing
[[redirects]]
  from = "https://*.2nd.exchange/*"
  to = "https://2nd.exchange/.netlify/functions/next-middleware/:splat"
  status = 200
  force = true

# Fallback for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
