import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { UserProvider } from "@/components/auth/user-provider";
import { Toaster } from "@medusajs/ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "2nd.exchange - A proffesional platform for showcasing your work!",
  description: "Generated by efforts that you cannot imagine",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <main className="min-h-screen">
            {children}
          </main>
          <Footer />
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
